### ISSUE TITLE
After application, Windows Updates and Powershell no longer works

### ISSUE THREAD

**Issue by SUBnet192** [simeononsecurity/Standalone-Windows-Server-STIG-Script#3]
PSRepository is blank, and Windows Update fails on Server 2019 standalone. Unable to add PSRepository, no errors, but still blank after registering default.

**Comment by simeononsecurity** [comment]
> PSRepository is blank, and Windows Update fails on Server 2019 standalone. Unable to add PSRepository, no errors, but still blank after registering default.

What configuration options for the script did you use?
Can you send us any errors logs for the related issues?

**Comment by SUBnet192** [comment]
default, apply all. ran the iex one-liner.
I can't find any logs, that's the issue.
Symptoms seem to point to SSL/TLS issue but again, can't find anything. I'm used to the STIG GPOs, I deploy them regularly at various clients, first time I tried your script for standalone :) Seems to do a good job but the finer details elude me.

**Comment by simeononsecurity** [comment]
We'll admit we didn't test our latest changes. Though they shouldn't have affected anything differently as we test as if all changes were run anyways and the latest change was just to let you chose options you don't want. Give us a few we'll retest to see if something is up.
Are you running anything non standard? Like a selfhosted psrepository or wsus?

**Comment by SUBnet192** [comment]
Nope. My current findings seem to point to cryptography, I have the same symptoms as this
https://learn.microsoft.com/en-us/answers/questions/354230/windows-update-fail-0x80072efe

**Comment by SUBnet192** [comment]
That was it. After deleting the ECC regkey and rebooting, everything works again.
'SOFTWARE\Policies\Microsoft\Cryptography\Configuration\SSL\00010002\EccCurves'

**Comment by SUBnet192** [comment]
Thanks for the great tool, it's a timesaver :D

**Comment by simeononsecurity** [comment]
You're right. I've also verified your findings. Can't beleive we didn't notice that before. That's so odd..
That's one we'll have to change and just leave the finding open so that people can fix it on their own knowing the issue at hand.

**Comment by simeononsecurity** [comment]
Glad to be of help @SUBnet192

**Comment by simeononsecurity** [comment]
Updated the repo to prevent this from happening
https://github.com/simeononsecurity/Standalone-Windows-Server-STIG-Script/commit/a4a9e8b213a8a0562212aefa1319004da1a455ae

**Comment by SUBnet192** [comment]
This issue is still happening. Just applied the hardening settings and the ECCCurves setting was modified.

**Comment by simeononsecurity** [comment]
Meaning you applied them and the fix for the ecc curves did not prevent the issue from occuring or?

**Comment by simeononsecurity** [comment]
Alter the settings at 
Configure the policy value for Computer Configuration >> Administrative Templates >> Network >> SSL Configuration Settings >> "ECC Curve Order" to "Enabled" with "ECC Curve Order:" including the following in the order listed:
Likely gpo is re implementing the changes
